FROM node:8


# TODO:
# Create a working directory.


# TODO:
# Copy package.json and package-lock.json to the working directory. 


# TODO:
# Install dependencies by running `npm install`.


# TODO:
# Copy everything in the local current directory to the working directory of the image.
# .dockerignore will ignore all the unnecessary files for you.


# TODO:
# Expose port 8080.


# Command to start node.js server.
CMD [ "npm", "start" ]